/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package registromascotas;

/**
 *
 * @author yese
 */
public class REGISTRO extends javax.swing.JFrame {

    /** Creates new form REGISTRO */
    public REGISTRO() {
        initComponents();
         this.setResizable(false);
        this.setLocationRelativeTo(null);
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registropropietario = new javax.swing.JButton();
        registromascota = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idpropietario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(486, 270));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registropropietario.setBackground(new java.awt.Color(102, 255, 255));
        registropropietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IMAGEN.png"))); // NOI18N
        registropropietario.setText("Registro Propietario");
        registropropietario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registropropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registropropietarioActionPerformed(evt);
            }
        });
        jPanel1.add(registropropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, 53));

        registromascota.setBackground(new java.awt.Color(102, 255, 255));
        registromascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IMAGEN1.png"))); // NOI18N
        registromascota.setText("Registro Mascota");
        registromascota.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registromascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registromascotaActionPerformed(evt);
            }
        });
        jPanel1.add(registromascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 180, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID PROPIETARIO");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 30));

        idpropietario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        idpropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpropietarioActionPerformed(evt);
            }
        });
        jPanel1.add(idpropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registropropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registropropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registropropietarioActionPerformed

    private void registromascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registromascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registromascotaActionPerformed

    private void idpropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTRO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTRO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idpropietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registromascota;
    private javax.swing.JButton registropropietario;
    // End of variables declaration//GEN-END:variables

}
